version: '3.8'

services:
  app:
    container_name: chat
    build: .
    command: sh -c "python core/manage.py migrate && python core/manage.py runserver 0.0.0.0:8000"

    depends_on:
      - db

    volumes:
      - ./:/var/www/

    ports:
      - "8000:8000"

  db:
    container_name: chat_db

    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

    ports:
      - "5433:5433"

  redis:
    image: redis:latest
    container_name: redis

volumes:
  postgres_data: